env:
  global:
    - CC_TEST_REPORTER_ID=3a1f7b8bb5a15f6cef89ea123b3825813e94c5f7aa9752f6f9083ab92bfb9637
language: node_js
node_js: "node"
cache: yarn
git:
  depth: 5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn run test-eslint
  - yarn run test-jest-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT